export default function LoadingComponent() {
  return (
    <div>
      <div className="loadingio-spinner-pulse-xb2mbganag">
        <div className="ldio-7vyikdvdygi">
          <div />
          <div />
          <div />
        </div>
      </div>
      <style
        type="text/css"
        dangerouslySetInnerHTML={{
          __html:
            "\n@keyframes ldio-7vyikdvdygi-1 {\n  0% { top: 36px; height: 128px }\n  50% { top: 60px; height: 80px }\n  100% { top: 60px; height: 80px }\n}\n@keyframes ldio-7vyikdvdygi-2 {\n  0% { top: 41.99999999999999px; height: 116.00000000000001px }\n  50% { top: 60px; height: 80px }\n  100% { top: 60px; height: 80px }\n}\n@keyframes ldio-7vyikdvdygi-3 {\n  0% { top: 48px; height: 104px }\n  50% { top: 60px; height: 80px }\n  100% { top: 60px; height: 80px }\n}\n.ldio-7vyikdvdygi div { position: absolute; width: 30px }.ldio-7vyikdvdygi div:nth-child(1) {\n  left: 35px;\n  background: #93dbe9;\n  animation: ldio-7vyikdvdygi-1 1s cubic-bezier(0,0.5,0.5,1) infinite;\n  animation-delay: -0.2s\n}\n.ldio-7vyikdvdygi div:nth-child(2) {\n  left: 85px;\n  background: #689cc5;\n  animation: ldio-7vyikdvdygi-2 1s cubic-bezier(0,0.5,0.5,1) infinite;\n  animation-delay: -0.1s\n}\n.ldio-7vyikdvdygi div:nth-child(3) {\n  left: 135px;\n  background: #5e6fa3;\n  animation: ldio-7vyikdvdygi-3 1s cubic-bezier(0,0.5,0.5,1) infinite;\n  animation-delay: undefineds\n}\n\n.loadingio-spinner-pulse-xb2mbganag {\n  width: 200px;\n  height: 200px;\n  display: inline-block;\n  overflow: hidden;\n  background: transparent;\n}\n.ldio-7vyikdvdygi {\n  width: 100%;\n  height: 100%;\n  position: relative;\n  transform: translateZ(0) scale(1);\n  backface-visibility: hidden;\n  transform-origin: 0 0; /* see note above */\n}\n.ldio-7vyikdvdygi div { box-sizing: content-box; }\n/* generated by https://loading.io/ */\n",
        }}
      />
    </div>
  );
}
